version: '3'

services:
    weather-back-end:
        build: ./WeatherApi
        ports:
            - 3000:3000

    weather-front-end:
        build: ./Client
        ports:
            - 80:80
        depends_on:
            - weather-back-end
